"""Add status_change table

Revision ID: 088ece271019
Revises: b82af79df226
Create Date: 2026-07-10 23:04:49.801159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088ece271019'
down_revision = 'b82af79df226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_change', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_change_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_change', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_change_submission_id'))

    op.drop_table('status_change')
    # ### end Alembic commands ###
