"""Add editorial board profile fields to User

Revision ID: 1c96bd151161
Revises: c5c8dafd7b96
Create Date: 2026-07-12 01:03:38.838362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c96bd151161'
down_revision = 'c5c8dafd7b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_category', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('board_display_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('board_roles', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('board_affiliation', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('board_photo', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('board_photo')
        batch_op.drop_column('board_affiliation')
        batch_op.drop_column('board_roles')
        batch_op.drop_column('board_display_name')
        batch_op.drop_column('board_category')

    # ### end Alembic commands ###
