"""Initial schema

Revision ID: 2bd180b010a9
Revises: 
Create Date: 2026-07-10 21:45:41.265297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd180b010a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_editor', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track', sa.String(length=100), nullable=False),
    sa.Column('keywords', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('manuscript_path', sa.String(length=500), nullable=False),
    sa.Column('graphical_abstract_path', sa.String(length=500), nullable=False),
    sa.Column('cover_letter_path', sa.String(length=500), nullable=False),
    sa.Column('supplementary_path', sa.String(length=500), nullable=True),
    sa.Column('supplementary_description', sa.String(length=500), nullable=True),
    sa.Column('corresponding_name', sa.String(length=200), nullable=False),
    sa.Column('corresponding_phone', sa.String(length=50), nullable=False),
    sa.Column('corresponding_email', sa.String(length=255), nullable=False),
    sa.Column('corresponding_whatsapp', sa.String(length=50), nullable=True),
    sa.Column('corresponding_org', sa.String(length=300), nullable=False),
    sa.Column('corresponding_dept', sa.String(length=200), nullable=True),
    sa.Column('corresponding_city', sa.String(length=150), nullable=False),
    sa.Column('corresponding_state', sa.String(length=150), nullable=True),
    sa.Column('corresponding_country', sa.String(length=10), nullable=False),
    sa.Column('submission_role', sa.String(length=50), nullable=False),
    sa.Column('author_category', sa.String(length=50), nullable=False),
    sa.Column('coi_status', sa.String(length=10), nullable=False),
    sa.Column('coi_details', sa.Text(), nullable=True),
    sa.Column('ethics_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_user_id'), ['user_id'], unique=False)

    op.create_table('co_author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('org', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('co_author', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_co_author_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('co_author', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_co_author_submission_id'))

    op.drop_table('co_author')
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_user_id'))

    op.drop_table('submission')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
