"""Add session_version to user

Revision ID: b82af79df226
Revises: 2bd180b010a9
Create Date: 2026-07-10 22:32:18.416676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82af79df226'
down_revision = '2bd180b010a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (this column is NOT NULL and
    # the table may already have data) — dropped right after so it doesn't
    # linger as a schema-level default beyond this one-time backfill; the
    # application already supplies session_version=1 for every new row.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_version', sa.Integer(), nullable=False, server_default='1'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('session_version', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('session_version')

    # ### end Alembic commands ###
