"""Add declined_at to review_assignment

Revision ID: c5c8dafd7b96
Revises: d34c1d68e75e
Create Date: 2026-07-11 19:55:09.791417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c8dafd7b96'
down_revision = 'd34c1d68e75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('declined_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_assignment', schema=None) as batch_op:
        batch_op.drop_column('declined_at')

    # ### end Alembic commands ###
