"""Add is_reviewer and review_assignment table

Revision ID: d34c1d68e75e
Revises: 088ece271019
Create Date: 2026-07-11 19:16:34.877348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34c1d68e75e'
down_revision = '088ece271019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('recommendation', sa.String(length=30), nullable=True),
    sa.Column('comments_to_author', sa.Text(), nullable=True),
    sa.Column('comments_to_editor', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'reviewer_id', name='uq_review_assignment_submission_reviewer')
    )
    with op.batch_alter_table('review_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_assignment_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_assignment_submission_id'), ['submission_id'], unique=False)

    # server_default backfills existing rows (this column is NOT NULL and
    # the table may already have data) — dropped right after so it doesn't
    # linger beyond this one-time backfill; the app already supplies
    # is_reviewer=False for every new row.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reviewer', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_reviewer', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_reviewer')

    with op.batch_alter_table('review_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_assignment_submission_id'))
        batch_op.drop_index(batch_op.f('ix_review_assignment_reviewer_id'))

    op.drop_table('review_assignment')
    # ### end Alembic commands ###
